name: Build Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  IMAGE_NAME: wg-obfuscator

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v6, linux/386, linux/ppc64le, linux/s390x]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare filename and tag
        id: prep
        run: |
          SAFE_NAME="${{ env.IMAGE_NAME }}-${{ matrix.platform }}"
          SAFE_NAME=$(echo "$SAFE_NAME" | sed 's|linux/||;s|/|-|g')
          echo "name=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Build per-arch image and export as tar
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.name }}
          platforms: ${{ matrix.platform }}
          outputs: type=docker,dest=${{ steps.prep.outputs.name }}.tar
          context: .

      - name: Upload image tar
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prep.outputs.name }}.tar
          path: ${{ steps.prep.outputs.name }}.tar
