name: Build & Publish Multiarch Docker Image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: wg-obfuscator
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386,linux/ppc64le,linux/s390x

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        id: prep
        run: |
          VERSION=$(grep VERSION wg-obfuscator.h | awk '{print $3}' | sed 's|"||g')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push multiarch image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            clustermeerkat/${{ env.IMAGE_NAME }}:latest
            clustermeerkat/${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.version }}
          platforms: ${{ env.PLATFORMS }}
          context: .
